#!/bin/sh
APPDIR=`dirname $0`;
LIBS=$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar:$APPDIR/lib/gwtx-1.5-20081912.jar
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/build/classes:$LIBS" com.google.gwt.dev.GWTShell -out "$APPDIR/build/www" "$@" org.gwt.beansbinding.Main/Main.html;
